src/app/business/routes/algo/sagas/index.js, src/app/business/routes/dataset/sagas/index.js, src/app/business/routes/model/sagas/index.js, src/app/business/routes/objective/sagas/index.js
Credentials were not included in requests made for the searchbar, which meant that there was no autocomplete of values (calls were rejected).
=> Include credentials in requests made for the searchbar

.yarnrc
This is to fix an issue we have with docker hub where the `yarn install` fails with timeout errors.
=> Increase network timeout limit during yarn install

.travis.yml
Since TravisCI is executing helm 3.0, and according to the migrate document https://helm.sh/docs/topics/v2_v3_migration/ the --client-only is not supported anymore as it is the default behavior.
=> travis ci fix helm init 

src/app/business/routes/model/bundleByTag.js, src/app/business/routes/model/components/detail/components/modelSummary.js, src/app/business/routes/model/components/detail/components/tabs/index.js, src/app/business/routes/model/selector.js, src/app/business/search/fixtures/traintuples.js
The `cancel-compute-plan` feature introduces a new `canceled` status for tuples that needs to be handled properly.
Related PR in the backend: https://github.com/SubstraFoundation/substra-backend/pull/65
=> Handle new "canceled" status

src/app/business/routes/model/components/detail/components/tabs/index.js, src/app/business/search/selector.js
The model detail pane used to display the "training" score of each traintuple. Since there's now no evaluation step attached to the training there is also no score. I removed the mention of this score.
I also fixed a "reduce" that missed its initial value.
=> Remove non-existing traintuple score

webpack/utils/plugins/definePlugin.js
Adding API_URL to definePlugin made the skaffold version of the frontend fail. 
In the bundle that contained `user/api.js`, the global `API_URL` variable was undefined, which meant that login calls were made to `http://substra-frontend.node-1.com/undefined/user/login`.
Since adding this API_URL to definePlugin was required for electron, I modified the code to add it only in that case.
=> Fix api url k8s

src/app/business/common/routes/web.js
The chunkName callback relied on a regex with a positive lookbehind clause which isn't supported in FF at the moment. Since we can predict the output of the regex replace (model will never contain a `/`), we can replace it with the target value.
=> Simpler chunk name

charts/substra-frontend/requirements.lock, charts/substra-frontend/requirements.yaml
StatefulSet in apps/v1beta2 is deprecated in kubernetes 1.16 and we should now use apps/v1.
This modification is backward compatible with kubernetes 1.15.
=> Bump redis chart

webpack/utils/plugins/definePlugin.js
The `IS_ELECTRON` value was the string `"false"` by default instead of being the string `false`, which made the check on L16 return true everytime.
=> Fix skaffold build

.dockerignore, Dockerfile, README.md, package.json
We ran into a bug created by node 13: https://github.com/babel/babel/issues/11216
By specifying which version to use in the dockerfiles and using the yarn.lock for packages, we can make sure we control the content of the container.
=> Specify which version of node to use

.env, README.md, charts/substra-frontend/requirements.lock, charts/substra-frontend/requirements.yaml, charts/substra-frontend/templates/deployment.yaml, charts/substra-frontend/values.yaml, config/default.js, docker-compose.yaml, packages/ssr/package.json, src/server/render.js, tools/deploy_template.js, yarn.lock
With the introduction of user credentials, our redis cache use has been reduced to caching on the `/404` route. This very minimal benefit was made at the cost of added complexity in our development and deployment setups (needs for a redis instance) and required quite a bit of code and documentation.
This PR removes the redis cache and the dependency on redis entirely.
This change can be tested with:
* local env: `yarn start` should not fail if redis isn't present locally
* docker-compose: no more `redis` container
* skaffold dev: no more `redis` container
=> Remove redis cache

src/app/business/common/sagas/index.js, src/app/business/routes/algo/sagas/index.js, src/app/business/routes/dataset/sagas/index.js, src/app/business/routes/model/api.js, src/app/business/routes/model/sagas/index.js, src/app/business/routes/objective/sagas/index.js
There was a lot of duplicated code in our sagas, as well as inconsistent naming throughout. This PR simplifies this all by:
- creating a handy `withJWT` decorator
- providing saga factories for default behavior
- mutualizing code between list and persistent sagas (was doing the exact same thing but with different actions)
=> Refactor sagas

src/app/business/common/components/detail/components/metadata.js, src/app/business/routes/algo/components/detail/components/metadata.js, src/app/business/routes/dataset/components/detail/components/metadata.js, src/app/business/routes/model/components/detail/components/metadata.js, src/app/business/routes/model/components/detail/components/testtupleSummary.js, src/app/business/routes/objective/components/detail/components/metadata.js
This PR aims to add assets' metadata field to the frontend.
These metadata are currently displayed as follows.
When there are metadata:
When there are no metadata:
=> Add user metadata

src/app/business/common/reducers/item.js, src/app/business/common/sagas/index.js, src/app/business/common/selector.js, src/app/business/routes/algo/reducers/item.js, src/app/business/routes/algo/sagas/index.js, src/app/business/routes/dataset/reducers/item.js, src/app/business/routes/dataset/sagas/index.js, src/app/business/routes/objective/reducers/item.js, src/app/business/routes/objective/sagas/index.js
Companion PR to https://github.com/SubstraFoundation/substra-backend/pull/312
The changes affect 2 actions:
* selecting an item in a list and fetching/displaying this item's details
* displaying the description of an item
In order to validate the PR, you just have to make sure these actions still work as expected (no errors, no missing data).
=> Use key instead of pkhash

packages/ssr/package.json, yarn.lock
This fixes a prototype pollution issue reported by SNYK: https://snyk.io/vuln/SNYK-JS-LODASH-590103
=> Bump lodash version

CHANGELOG.md, src/hooks/usePerfBrowser.ts
Fix CPs not being able to be unselected in CPs comparison page
=> fix: Broken unselection of CPs in comparison page

CHANGELOG.md, src/components/RefreshBanner.tsx, src/hooks/useHandleRefresh.ts, src/routes/algos/Algos.tsx, src/routes/computePlans/ComputePlans.tsx, src/routes/datasets/Datasets.tsx
From @maeldebon 
I updated `useHandleRefresh` to keep parameters on refresh.
Refresh banner is now getting ordering from url params in order to be able to sort compute plans properly.
=> feat: keep params on refresh

nginx/nginx.conf
Effectively, this removes the nginx version number from frontend error pages. This is only for production, it won't change anything on development
According to our security audit, we don't gain much from exposing this info, but it might give an attacker some help.
Asana task with more context: https://app.asana.com/0/1201599852028640/1202311798287732 (the parent task has a link to the full audit)
I tried it by accessing `/assets/` on the frontend, then updating and reloading the nginx configuration and accessing the same page again to check the server version number had disappeared.
A deeper question for you frontend experts is _why_ `/assets` returns a 403. I guess it's better than a directory of the folder, but I imagine a nice-looking 404 would be preferable.
=> chore(docker): remove superfluous info from server headers

CHANGELOG.md, src/hooks/useLocalStorageState.ts, src/routes/computePlans/ComputePlans.tsx
LINKED TO THIS [ASANA CARD](https://app.asana.com/0/1200346939311555/1202883398420791) and [ASANA CARD](https://app.asana.com/0/1200346939311555/1202937437974384)
The local storage values where not retrieved correctly.
- Add custom columns
- Add CP as favorite
- Log out
- Log in : you should see your favorites CP and customised columns
=> fix: CP columns and favorites disappear on logout

CHANGELOG.md, charts/substra-frontend/CHANGELOG.md, charts/substra-frontend/Chart.yaml, package-lock.json, package.json
-   Users management v1
-   Added license file
-   Removed references to close-source items
-   Change Customize Columns items icon color
-   Increase page size to 30
-   CP Workflow graph: Allow a higher min zoom to show more tasks
-   CP Workflow graph: update layout for predict tasks and test tasks
-   Change Connect branding to Substra
-   Add capital letter R to reset zoom button
-   Rename Connect to Substra in code and ci files
-   Change primary color from teal to blue
-   Keep filtering/ordering setup when refreshing an asset list page
-   Display all General customize columns by default
-   Elements being highlighted when drag and drop Customize Columns items
-   Can edit by deleting the input number in CP duration filter
-   CP duration filter is broken on refresh and for below …
=> chore(release): 0.33.0

CHANGELOG.md, e2e-tests/cypress/integration/computePlans.spec.js, src/routes/computePlanDetails/ComputePlanChart.tsx, src/routes/computePlanDetails/components/TabsNav.tsx, src/routes/computePlanDetails/components/TasksWorkflow.tsx
Testing the tabs Workflow and Performance with Cypress
**Important** : the cypress test are inconsistent : they fail from time to time, which make it very painful and hard to test. I investigated and this is due to an **untimely logout**. The token is blacklisted. This issue will be discussed with the team.
**NB**: With general tasks, the CP Tasks page will be modified soon : we will remove the type tabs (test, predict, train ...) and display all Tasks in one Table*.
For this reason, the test case "_CP > Tasks > any task's drawer_" will be tested when this change is done, in an other PR.
*this was discussed during the GT meeting of the last Friday 09-09-22.
=> feat: add Cypress tests for CP Workflow and Performances page

CHANGELOG.md, ci/cilib/docker.py
Before building docker image we check if a manifest with same tag already exists, if not found, then we build and push the docker image. It seems that when a manifest is not found, error returned by gcr was `no such manifest` and now on ghcr we receive the `manifest unknown` error, which was not handled.
Hopefully this will fix the release
=> ci: handle both gcr and ghcr manifest not found error

src/components/EmptyState.tsx, src/routes/computePlanDetails/components/UnavailableWorkflow.tsx
Ci is broken because of a Cypress test. The test is related to the empty workflow graph case. This PR made sure that the empty state is taken into account during the test.
No changelog needed.
=> fix: allow to test empty workflow graph

CHANGELOG.md, charts/substra-frontend/CHANGELOG.md, charts/substra-frontend/Chart.yaml, package-lock.json, package.json
-   Cypress tests for compute plan pages Workflow and Performances
-   Handle both gcr and ghcr manifest not found error in release workflow ci
=> chore(release): 0.34.0

CHANGELOG.md, src/libs/request.ts
withRetry function used in authenticatedGet was still using an outdated route for the refresh endpoint
=> fix: Fix outdated route in withRetry

CHANGELOG.md, src/routes/users/components/UpdateUserForm.tsx
When updating a user role, we do not see the description informations on the toast (name of the user mainly).
=> fix: show hidden user description on user update

CHANGELOG.md, src/modules/cpWorkflow/CPWorkflowLayout.spec.ts, src/modules/cpWorkflow/CPWorkflowLayout.ts, src/modules/cpWorkflow/CPWorkflowTypes.ts, src/routes/computePlanDetails/components/WorkflowTaskNode.tsx
[ASANA TASK](https://app.asana.com/0/1200346939311555/1203023779458048/f)
This is a preparatory work to removing the task categories.
- Now the layout algorithm does not rely on task categories. Instead some chains of tasks are identified as "secondary branches" to be stacked vertically (like it was before for the predict and the test tasks).
- Also, the category is not displayed anymore in the task header. (In a later PR we should modify the design, the header is not really useful anymore)
This relies on a backend change: new information is needed in the response to be able to identify those secondary branches (see the code for details)
Companion PRs:
- [backend](https://github.com/Substra/substra-backend/pull/477) 
- ~~substra~~: Not impacted
=> feat(workflow): Do not rely on task categories

CHANGELOG.md, src/routes/tasks/components/TaskInputsDrawerSection.tsx
Handle empty task inputs case : display an empty section/row.
Open a failed task drawer.
=> fix: empty inputs make the drawer crash

CHANGELOG.md, src/routes/tasks/components/ErrorAlert.tsx
Companion PRs:
- https://github.com/Substra/substra-backend/pull/483 (main PR)
- https://github.com/Substra/orchestrator/pull/38
- https://github.com/Substra/substra/pull/295
- https://github.com/Substra/substra-tests/pull/218
- https://github.com/Substra/substra-frontend/pull/116 (this PR)
- https://github.com/Substra/substra-documentation/pull/184
--- 
Previously, only execution errors had logs. Now, build errors have logs too.
=> feat: make container build error logs accessible

CHANGELOG.md, src/components/TasksTable.tsx, src/routes/computePlanDetails/ComputePlanTasks.tsx
Clicking a task in the task table on the cp details page previously navigated to the tasks page to open the task drawer. Now the task drawer is directly opened in cp details page.
=> fix: Open task drawer directly in cp details page

CHANGELOG.md, src/routes/login/Login.tsx
The login page had a handful of glitches:
* in the left section, horizontal padding was inconsistent
* in the left section, app version was displayed as a weird abbreviation: "vers." with no space between "vers." and the version number
* in the right section, on large screens, there was whitespace on the right hand side
* in the right section, the background image was not centered, making the person disappear on smaller screens
* in the right section, the "Learn more" link pointed to a github repo with no resources to learn more
* in the right section, the "Learn more" link markup was a div within a button within a link. It's changed into a simple link.
* https://app.asana.com/0/1200346939311555/1203091499867938
* https://app.asana.com/0/1200346939311555/1203030647785903
=> fix: UI and markup glitches on login page

CHANGELOG.md, src/components/layout/header/NewsFeedCard.tsx, src/modules/newsFeed/NewsFeedTypes.ts, src/modules/newsFeed/NewsFeedUtils.ts
Algo creation events are not needed in the newsfeed anymore. They're being removed from the values returned by the backend (see companion PR), this PR removes the code that was handling these events.
Companion PR: https://github.com/Substra/substra-backend/pull/514
=> fix: remove algo from newsfeed

CHANGELOG.md, src/components/ComputePlanProgressBar.tsx, src/components/ComputePlanTaskStatuses.tsx, src/components/Duration.tsx, src/components/OmniSearch.tsx, src/components/Status.tsx, src/components/TableFilters/TaskStatusTableFilter.tsx, src/components/TasksTable.tsx, src/components/Timing.tsx, src/hooks/useDownloadPerfCsv.ts, src/libs/status.ts, src/modules/common/CommonTypes.ts, src/modules/common/CommonUtils.ts, src/modules/computePlans/ComputePlanUtils.ts, src/modules/computePlans/ComputePlansApi.ts, src/modules/computePlans/ComputePlansSlice.ts, src/modules/cpWorkflow/CPWorkflowLayout.spec.ts, src/modules/cpWorkflow/CPWorkflowLayout.ts, src/modules/cpWorkflow/CPWorkflowTypes.ts, src/modules/cpWorkflow/CPWorkflowUtils.ts, src/modules/tasks/TasksApi.ts, src/modules/tasks/TasksSlice.ts, src/modules/tasks/TasksTypes.ts, src/routes/computePlanDetails/components/TasksWorkflow.tsx, src/routes/computePlanDetails/components/WorkflowTaskNode.tsx, src/routes/tasks/components/DrawerSectionOutModelEntryContent.tsx, src/routes/tasks/components/ErrorAlert.tsx, src/routes/tasks/components/LogsModal.tsx, src/routes/tasks/components/TaskInputsDrawerSection.tsx, src/routes/tasks/components/TaskOutputsDrawerSection.tsx
Renames all tuple things into task things. This is pure code maintenance to avoid dragging an old naming in the future.
There was also a couple of aggregate and composite names still there, I removed them as well.
=> chore: rename tuple things into task things

CHANGELOG.md, package-lock.json, package.json, vite.config.ts
`npm install` yielded the following messages:
```
npm WARN deprecated source-map-resolve@0.6.0: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated @vitejs/plugin-react-refresh@1.3.6: This package has been deprecated in favor of @vitejs/plugin-react
npm WARN deprecated react-style-singleton@2.2.0: wrong managing of dynamic styles
```
The main culprit was @vite/plugin-react-refresh that has been deprecated. The new @vitejs/plugin-react package not only handles the refresh but also makes the vite-react-jsx unnecessary. 
In order to use this new plugin, I've had to upgrade vite to the new 3.x.x version, following the [migration guide](https://vitejs.dev/guide/migration.html)
This also lead to needing to update …
=> fix: warnings during npm install

CHANGELOG.md, src/routes/users/components/UpdateUserForm.tsx, src/routes/users/components/UserDrawer.tsx
Fixes https://github.com/Substra/substra-frontend/issues/130
The check for "last admin" status of the currently edited user had a couple of issues:
1. it was pretty inefficient as it needed to fetch ALL users from the backend, and then check that there is only one admin. I tackled this by adding a filter on role in the backend and then just getting the count on the first page of results for the `/users?role=ADMIN`request. See https://github.com/Substra/substra-backend/pull/517
2. there was a race condition between the multiple useEffects. This is solved by having a single useEffect that both fetches the user to edit and then checks the "is last admin" status before setting loading to false.
=> fix: last admin check

src/modules/cpWorkflow/CPWorkflowLayout.spec.ts, src/modules/cpWorkflow/CPWorkflowLayout.ts, src/modules/cpWorkflow/CPWorkflowTypes.ts, src/modules/cpWorkflow/CPWorkflowUtils.ts, src/routes/computePlanDetails/components/TasksWorkflow.tsx, src/routes/computePlanDetails/components/WorkflowTaskNode.tsx
A side effect of extracting information from the db was that the asset kind names was different than the hardcoded ones.
Also, some following tasks have 2 edges connecting them: this implies to update the way to find secondary branches.
Finally, 3 fields in the response changes names:
- for maintenance purpose, we decided to match the name in db: id -> identifier
- implementation constraints made us change inputs -> inputs_specs and outputs -> outputs_specs
companion PR:
[backend](https://github.com/Substra/substra-backend/pull/486)
=> fix(workflow): Graph is built from info from db (not hardcoded in/out)

CHANGELOG.md, charts/substra-frontend/CHANGELOG.md, charts/substra-frontend/Chart.yaml, package-lock.json, package.json
-   Documentation link in user menu (#132)
-   Removed task categories from the frontend (#119)
-   Open task drawer directly in cp details page (#122)
-   Algo creation events aren't included in newsfeed anymore (#127)
-   Renamed any tuple thing into a task thing (#129)
-   UI and markup glitches on login page (#123)
-   Check for "last admin" when editing a user (#131)
-   Warnings during npm install (#126)
=> chore: Release 0.37.0

CHANGELOG.md, src/modules/computePlans/ComputePlansTypes.ts
Signed-off-by: Serge Bouchut <serge.bouchut@owkin.com>
API has changed: we now have a flat field `failed_task_key` (as `failed_task.category` has been removed).
See: https://github.com/Substra/substra-backend/pull/525
=> feat: update cp failed task key

CHANGELOG.md, src/modules/perf/PerformancesTypes.ts, src/modules/series/SeriesTypes.ts, src/modules/series/SeriesUtils.ts
Use the new output_identifier from compute plan performance endpoint to build series groups to display performance charts
=> Add metric output_identifier to series grouping logic

automated-e2e-tests/skaffold.yaml, skaffold.yaml
Frontend skaffold configuration refers to wrong host. Images are built and push to gcr.io and this forces to handle the frontend differently in the [ci repo](https://github.com/owkin/substra-ci/blob/ea2d52719753cf2327df90e539e3ad787610058d/ci/config.py#L130). (internal link)
This PR removes this difference.
[Internal] See thread : https://owkin.slack.com/archives/C03K3JBS7H7/p1662643065715729
Companion PR:
- https://github.com/owkin/substra-ci/pull/79
=> ci: keep gcr to host skaffold image build

CHANGELOG.md, src/modules/users/UsersUtils.ts, src/routes/resetPassword/components/ResetForm.tsx, src/routes/users/components/CreateUserForm.tsx, src/routes/users/components/PasswordInput.tsx, src/routes/users/components/RoleInput.tsx, src/routes/users/components/UpdateUserForm.tsx, src/routes/users/components/UsernameInput.tsx
Companion PR: https://github.com/Substra/substra-backend/pull/524
- fixes a typo (`hasCorrectLenght `)
- renames unclear method `checkPasswordErrors` into `isPasswordValid`
- fixes the valid status of the PasswordInput component
- displays toast and closes drawer only once the create/update call has returned. This also allows the list to be refreshed only once the creation/update has finished, which makes sure it contains the most up-to-date data
- handles creation failure (error toast + do not close drawer)
- disables create button if form is not valid
- adds a loading status on the create button when the call is ongoing
- disable inputs during update/creation
=> fix: user creation/edition validation

CHANGELOG.md, src/components/PerfBrowser.tsx, src/components/PerfDetails.tsx, src/components/PerfList.tsx, src/hooks/usePerfBrowser.ts, src/modules/series/SeriesUtils.ts
Fix 2 bugs pertaining to the new way of grouping series for the performance page. Before the series where grouped using the metricName, but now they are grouped using the pair metricKey(=algoKey)/metricOutputIdentifier. This introduced 2 bugs : 
- selecting/unselecting CPs in compare page was creating duplicate of performance cards. This was because when passing to the new grouping method we passed from a string (metricName) to an array ([algoKey, metricOutputIdentifier]) and the `Set` object that stocks unique values doesn't handle arrays in the same way. Fixed with stringifying & parsing the pair in the Set instead of using an array.
- with the new method, it is now possible to have several groups with the same metricName, meaning several performance cards in the performance browser. …
=> fix: series grouping & perf details serie

CHANGELOG.md, src/components/TableFilterTags.tsx, src/components/TableFilters/CreatorTableFilter.tsx, src/components/TableFilters/TableFilterCheckboxes.tsx, src/features/customColumns/CustomColumnsUtils.ts, src/hooks/useSyncedState.ts, src/modules/computePlans/ComputePlansTypes.ts, src/routes/computePlanDetails/components/DetailsSidebar.tsx, src/routes/computePlans/ComputePlans.tsx, src/routes/computePlans/components/ComputePlanTHead.tsx, src/routes/computePlans/components/ComputePlanTr.tsx
Companion PR backend : https://github.com/Substra/substra-backend/pull/511
Adding the creator field in the compute plan page first. This implies:
- Adding a creator column
- Adding a creator field in the cp detail page
- Allow filtering on a cp creator
NB: in the backend, the proposition we made was to use creator is `null` for the external users, as this value is not registered in the orchestrator. This supposition has to be validated in the next Architecture Advisory Forum.
[ASANA TASK](https://app.asana.com/0/1200346939311555/1203055070399486)
=> feat : add cp creator data

CHANGELOG.md, src/modules/datasets/DatasetsTypes.ts
Remove test_only property from datasample type as it now deprecated and being removed from all repositories.
=> chore: Remove test_only property from datasample type

vite.config.ts
Signed-off-by: SdgJlbl <sarah.diot-girard@owkin.com>
When launching the frontend locally, either using `npm run dev` or the provided Dockerfile, `vite` displays a clickable url which points to `http://127.0.0.1:3000/`. Yet, the frontend can be accessed locally at `http://substra-frontend.org-1.com:3000`.  
The provided change allows for the displayed url to match what should be accessed. 
I am unsure if this change could be impacting other parts of the frontend application, due to my inexperience with the codebase.
=> chore: change url displayed by vite in local

CHANGELOG.md, charts/substra-frontend/CHANGELOG.md, charts/substra-frontend/Chart.yaml, package-lock.json, package.json
-   CP creators are available data (#124)
-   Contributing, contributors & code of conduct files (#157)
-   Get tasks inputs & outputs assets from new endpoints (#144)
-   Change url displayed by vite in local (#163)
-   test_only property from datasample type (#158)
=> chore: Release 0.39.0

.github/ISSUE_TEMPLATE/bug_report.yaml, .github/ISSUE_TEMPLATE/config.yml, .prettierignore
Signed-off-by: SdgJlbl <sarah.diot-girard@owkin.com>
Add templates for issues on GitHub.
Include a bug report form, a link to the documentation for documentation improvements, a link to Substra Slack for questions, and the option to open a blank (non templated) issue for all other needs.
=> chore: add issues templates

CHANGELOG.md, src/routes/tasks/components/TaskInputsDrawerSection.tsx, src/routes/tasks/components/TaskOutputsDrawerSection.tsx
When opening task drawer from the compute plan tasks list, the inputs & outputs weren't correctly fetched.
=> fix: Fix task i/o display when opened from the cp tasks list

CHANGELOG.md, src/components/TableFilters/CreatorTableFilter.tsx
Ordering username list in creator filter used the hook useOrdering() which was interfering with the ordering of the CP table. Removed the hook's use as it is not necessary to call the user list in username order.
=> fix: CP ordering by creation date

CHANGELOG.md, src/libs/utils.ts, src/modules/perf/PerformancesTypes.ts, src/modules/series/SeriesTypes.ts, src/modules/series/SeriesUtils.ts
- https://github.com/Substra/substra-backend/pull/614
In the backend, a ComputeTask was still linked with `data_samples` and `data_manager`, which were accessible in the `performance.compute_task` object. This has been removed as the planned way to access these objects is through `ComputeTaskInput`/`ComputeTaskOutput`.
=> chore: remove `ComputeTask` pr-GT links

CHANGELOG.md, src/modules/common/CommonUtils.ts, src/modules/series/SeriesSlice.ts
In the perforamnce page, we fetch all performances (as `pageSize: 0` returns all results and not 0 results) before refetching them using the pagination
- https://github.com/Substra/substra-backend/pull/611
=> fix: improve perf loading

CHANGELOG.md, src/hooks/usePerfBrowser.ts
In compute plan details page & compare page, if perf was 0 it displayed as "-" instead of "0.000".
=> fix: Fix perf displaying as - when value is 0

CHANGELOG.md, src/assets/chakraTheme.ts, src/components/ApiToken.tsx, src/components/layout/header/ApiKey.tsx, src/components/layout/header/ApiTokens.tsx, src/components/layout/header/Header.tsx, src/modules/bearerTokens/BearerTokenApi.ts, src/modules/bearerTokens/BearerTokenTypes.ts, src/modules/bearerTokens/BearerTokenUtils.ts, src/modules/me/MeSlice.ts, src/modules/me/MeTypes.ts, src/routes/login/components/LoginForm.tsx
Add mechanism to handle a new authentication flow: single sign-on (SSO) through OpenID Connect (OIDC).
Changes:
- on the login page, we query the `/info` endpoint to see whether SSO is available, and if so present a button. All the button does is redirect to the backend at `/oidc/authenticate?next={some frontend page}`. The backend does everything else
- add the current username in the header menu, because with SSO the username is not obvious
- add an "API tokens" modal (in the header menu) so SSO users can use the library (they don't have a password).
In the future we will deprecate logging in on the command line, and that modal will be a nice interface for creating and managing API tokens. Probably.
Issues: _(to be fixed in a future PR, presumably)_
- active tokens make too many …
=> feat: add SSO

CHANGELOG.md, src/components/TasksTable.tsx
Fix bug in CP tasks table where using the ordering feature to order by shortest or longest task is giving the inverse of the expected result.
=> fix: Inverted duration filter in tasks table

.github/pull_request_template.md
Removing entirely mentions of files not accessible to the open source community
=> chore: Remove mention of Asana in gh PR template

CHANGELOG.md, src/routes/computePlanDetails/components/CancelComputePlanDialog.tsx, src/routes/computePlanDetails/components/CancelComputePlanMenuItem.tsx, src/routes/computePlanDetails/hooks/useCancelComputePlan.tsx
Previously, on uncancellable CPs, a tooltip informed the user on the possibilities of why a CP could be uncancellable (namely not the permissions because of different organization or not the good status, aka already done, failed, etc). 
With this PR, tooltip will inform the user on why this particular CP is not cancellable, prioritizing permissions (i.e : if a cp is not cancellable for permissions AND status, tooltip will just inform about the permission reason).
Also a minor change on the alert describing what's gonna happen to the tasks when cancelling a CP.
=> feat: cp uncancelable info

CHANGELOG.md, src/components/table/TasksTable.tsx, src/routes/computePlanDetails/workflow/CPWorkflowLayout.spec.ts, src/routes/computePlanDetails/workflow/components/WorkflowTaskNode.tsx, src/types/CPWorkflowTypes.ts
Today it's very hard for a user to quickly get what is inside the task, both in the workflow tab or when looking at a task list.
This PR adds the function name for each task in the workflow & in the tasks table.
Companion PR : https://github.com/Substra/substra-backend/pull/635
=> feat: Add functionName in workflow nodes & tasks table

CHANGELOG.md, src/components/PerfDownloadButton.tsx, src/features/perfBrowser/PerfBrowser.tsx, src/features/perfBrowser/PerfDetails.tsx, src/features/perfBrowser/PerfList.tsx, src/features/perfBrowser/PerfSidebarCommon.tsx, src/features/perfBrowser/PerfSidebarComputePlans.tsx, src/features/perfBrowser/PerfSidebarLines.tsx, src/features/perfBrowser/usePerfBrowser.ts, src/features/series/SeriesUtils.ts, src/routes/compare/components/CompareBreadcrumbs.tsx, src/routes/computePlanDetails/chart/components/ChartBreadCrumbs.tsx, src/types/PerformancesTypes.ts, src/types/SeriesTypes.ts
Performance asset were unique regarding their compute task key, and the function key they were computed from. Or, we want to have the possibility to have a function that outputs several performance and store them in the same task.
This implies two main things:
- Performance are now unique regarding the compute task key, the function key AND the output identifier
- The frontend must serialize regarding the identifier, and not the function key
The PR batch modify both the orchestrator and backend db in order to include the identifier as an additional unique condition.
In the backend, we use the ComputeTaskOutput as primary key directly.
- https://github.com/Substra/substra-backend/pull/634
- https://github.com/Substra/substra-tests/pull/251 (main)
- …
=> feat: serialize through identifier

CHANGELOG.md, src/routes/computePlanDetails/workflow/CPWorkflowLayout.ts
Tasks used to be ordered by creating a unique name created by joining the name of all the parents recursively. This recursivity wasn't scoped correctly to each cell, creating a recursion far too heavy that could make the browser crash when getting in the 500ish tasks.
This PR changes the way this part of the code is handled by removing the creation of a unique name per task entirely and placing tasks in cell based on their rank & closest parent in each cell.
I tried to test this on various CPs including edge cases such as test tasks being done on another org than the train ones.
=> fix: Change the way tasks are ordered in each cells

CHANGELOG.md, src/api/request.ts, src/components/table/TasksTable.tsx, src/features/series/useSeriesStore.tsx, src/features/tableFilters/CreatorTableFilter.tsx, src/routes/compare/Compare.tsx, src/routes/compare/useCompareStore.tsx, src/routes/computePlanDetails/useComputePlanStore.tsx, src/routes/computePlanDetails/workflow/ComputePlanWorkflow.tsx, src/routes/computePlanDetails/workflow/useWorkflowStore.ts, src/routes/computePlans/ComputePlans.tsx, src/routes/computePlans/useComputePlansStore.tsx, src/routes/datasets/Datasets.tsx, src/routes/datasets/useDatasetsStores.ts, src/routes/functions/Functions.tsx, src/routes/functions/useFunctionsStore.tsx, src/routes/tasks/useTasksStore.tsx, src/routes/users/Users.tsx, src/routes/users/useUsersStore.tsx, src/types/CommonTypes.ts
When making the change from redux to Zustand in PR #159, we lost the feature to cancel list calls when changing page in the app (although we kept the cancelling on reload). To be clearer, this means you don't want the frontend to finish making a big call to the backend for data concerning page A when you already moved on to page B. This feature is important for better performances in the case of big calls being made in the background for nothing.
Fixes FL-639
=> fix: Cancel list calls when reloading or changing page

CHANGELOG.md, src/features/auth/useAuthStore.ts
CPs stay selected in computePlans list page even after logging out. This creates situations where the user don't understand why he has CP selected when he comes back to the app. 
This PR fixes this by resetting the selected CPs after logging out.
Fixes FL-992
=> fix: Selected CPs now resetting after logout

CHANGELOG.md, src/components/DrawerSection.tsx
Hyper-parameters are not nicely shown when their names is too big. This PR fixes display by adding an ellipsis with a tooltip to still be able to read the full name.
=> fix: Hyperparameters bugged display when too big

CHANGELOG.md, src/components/table/TasksTable.tsx, src/routes/computePlans/components/ComputePlanTHead.tsx
Start and end date orderings in ComputePlans & Tasks lists was reversed
=> fix: Start & end date ordering being reversed

CHANGELOG.md, src/features/perfBrowser/usePerfBrowser.ts
Rounds makes more sense to look at FL performances graph, therefore this PR set `round` as default value if rounds they are available when `seriesGroupWithRounds` is updated (retrieved from backend).
Fixes FL-504
=> feat: change `XAxisMode` when `seriesGroupWithRounds` is updated

CHANGELOG.md, src/types/TasksTypes.ts
Currently, we represent task execution duration time as saving output time and reciprocally. This mislead users to think that there is a bug and that saving output is much slower than actually computing stuff, however this is not the case.
Fixes FL-570
=> fix: switch `task_execution` and `save_outputs` in `TaskStep`

src/features/perfBrowser/usePerfBrowser.ts
Fix for a bug where X Axis for the CP performances graphs kept going back to rounds even after selecting ranks.
=> fix: Ranks being unselectable in CP performances

CHANGELOG.md, charts/substra-frontend/CHANGELOG.md, charts/substra-frontend/Chart.yaml, package-lock.json, package.json
-   In perf views, set `round` as default if `seriesGroupWithRounds.length > 0`, otherwise `rank` (#205)
-   Task execution and output saving duration being switched (#214)
=> chore: release 0.43.0

CHANGELOG.md, src/api/ComputePlansApi.ts, src/features/series/useSeriesStore.tsx
- https://github.com/Substra/substra/pull/372
- https://github.com/Substra/substra-backend/pull/690
Remove pagination in performance endpoints, as we always need all of them. (cf linear description)
Note: alternative implementation would be to iterate on all pages in `<task_id>/perf/` in all case,  in the frontend and in the SDK.
Fixes FL-1092
=> fix: return all performances

docker/substra-frontend-tests/Dockerfile
CI is failing because e2e tests config file path has changed and was not updated in Dockerfile.
=> fix: e2e tests path in dockerfile

docker/substra-frontend-tests/Dockerfile
```js
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /e2e/cypress.config.ts
```
https://github.com/Substra/substra-frontend/pull/225#issuecomment-1642142034
```bash
$ docker build -t frontend-e2e -f docker/substra-frontend-tests/Dockerfile . && docker run -it --rm frontend-e2e
```
```bash
DevTools listening on ws://127.0.0.1:38653/devtools/browser/accec9b0-e84d-440c-9c65-1ccbc602cb7f
[453:0720/061528.900174:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
Couldn't find tsconfig.json. tsconfig-paths will be skipped
Cypress could not verify that this server is running:
> http://substra-frontend.org-1.com:3000
We are verifying this server because it has been configured as your baseUrl.
Cypress automatically waits until your server is …
```
=> fix(docker/e2e): add typescript in docker image

CHANGELOG.md, src/routes/users/components/UserDrawer.tsx
Page title (title visible in the browser tab) wasn't updated when opening the user drawer
Fixes FL-1096
=> fix: Document title when user drawer is active

CHANGELOG.md, src/routes/users/Users.tsx, src/routes/users/components/CreateUserForm.tsx, src/routes/users/components/UpdateUserForm.tsx, src/routes/users/components/UserDrawer.tsx, src/routes/users/useUsersStore.tsx
Fixes an error where the skeleton for the Users list was flashing each time we opened or closed the user drawer. This is because we used to refetch the list of users every time to check if a user had been created, deleted or updated. We now only fetch in the case of a creation or deletion. Updates are handled in the store directly and closing without actions or opening drawer no longer triggers a list fetch.
Fixes FL-1035
=> fix: Users list skeleton flashing when opening/closing drawer

CHANGELOG.md, src/App.tsx, src/api/UsersApi.ts, src/paths.ts, src/routes/users/Users.tsx, src/routes/users/components/UserAwaitingApproval.tsx, src/routes/users/components/UserAwaitingApprovalPage.tsx, src/routes/users/useUsersStore.tsx, src/types/UsersTypes.ts
Now users can be created without a channel, they are considered "unactivated users" or "User awaiting approval". They need to have their request accepted by an admin to become a normal user (or another admin)
Fixes FL-989
Connect with the SSO using an OIDC provider see: https://github.com/Substra/substra-backend/pull/609
This will create an unactivated user thus a request on the User page of any admin.
This is linked to this backend PR: https://github.com/Substra/substra-backend/pull/680
Also I made a POST to use with curl to easily create unactivated users without the OIDC provider (not to be merged in the backend).
=> feat: users awaiting approval

CHANGELOG.md, charts/substra-frontend/CHANGELOG.md, charts/substra-frontend/Chart.yaml, charts/substra-frontend/templates/deployment.yaml, nginx/nginx.conf
Changes to our helm chart to allow running on restricted security contexts (rootless, and with `readOnlyFileSystem` set.
Fixes FL-1102
Set the values:
```yaml
securityContext:
capabilities:
drop:
- ALL
readOnlyRootFilesystem: true
runAsNonRoot: true
runAsUser: 1000
```
with these settings, `skaffold run` fails on `main` but on this branch succeeds
I tried it on the target environment, it seems to work.
=> chore: allow running rootless and on readOnlyFileSystem

CHANGELOG.md, src/components/layout/header/HeaderNavigation.tsx
Currently clicking on the navigation tab that is already active does nothing if the user is on page 1 with no filters. This behavior seems weird to some, so this PR aims to make the asset list reload instead.
Fixes FL-515
=> feat: reload current asset list on nav tab click

CHANGELOG.md, src/routes/dataset/Dataset.tsx, src/routes/functions/components/FunctionDrawer.tsx, src/routes/tasks/components/TaskDrawer.tsx, src/routes/tasks/components/TaskInputsDrawerSection.tsx
Depending on its organisation, a user doesn't always have the permissions to download a function or opener. Currently, the user could still click on the download button when he didn't have the permissions, it's just that nothing would happen.
This PR aims for a clearer UI by disabling the download button and adding an informative tooltip when the user doesn't have permission to download.
Fixes FL-1072
=> feat: Add clearer ui for asset download permissions

CHANGELOG.md, src/routes/computePlanDetails/components/Actions.tsx, src/routes/computePlanDetails/components/CancelComputePlanMenuItem.tsx
This PR fixes the fact that the cancel compute plan button was unreachable on workflow due to z-index hierarchy. Also remove the "shouldwrapchildren" prop from the tooltip, which made the button only clickable on the text and not its whole width.
Fixes FL-1141
=> fix: Cancel CP button unreachable on workflow page

CHANGELOG.md, src/routes/tasks/components/TaskDrawer.tsx
Add duration in the duration section of the task drawer under the start date & end date.
Fixes FL-1183
=> feat: Add duration in task drawer

CHANGELOG.md, src/features/perfBrowser/usePerfBrowserColors.tsx
The compute plan charts are using a color rotation for the different lines. Since we changed the primary color when switching to Substra colors, the 1st and 3rd color of the rotation are too similar. This PR switches the order of the rotation so that the similar colors appear less often.
Fixes FL-1186
=> fix: color rotation in cp charts

e2e-tests/package-lock.json, e2e-tests/package.json
Bumps [cypress](https://github.com/cypress-io/cypress).
Updates `cypress` from 12.12.0 to 13.1.0
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a href="https://github.com/cypress-io/cypress/releases">cypress's releases</a>.</em></p>
<blockquote>
<h2>v13.1.0</h2>
<p>Changelog: <a href="https://docs.cypress.io/guides/references/changelog#13-1-0">https://docs.cypress.io/guides/references/changelog#13-1-0</a></p>
<h2>v13.0.0</h2>
<p>Changelog: <a href="https://docs.cypress.io/guides/references/changelog#13-0-0">https://docs.cypress.io/guides/references/changelog#13-0-0</a></p>
<h2>v12.17.4</h2>
<p>Changelog: <a href="https://docs.cypress.io/guides/references/changelog#12-17-4">https://docs.cypress.io/guides/references/changelog#12-17-4</a></p>
<h2>v12.17.3</h2>
<p>Changelog: …
=> chore(deps): Bump cypress to 13.1.0 in e2e-tests

CHANGELOG.md, src/api/DocsApi.ts, src/api/request.ts, src/components/layout/header/About.tsx, src/features/docs/useReleasesInfoStore.ts, src/paths.ts, src/types/DocsTypes.ts
It's often confusing for our partners what version of Substra they are running.
We introduced the "bundle" terminology and showed them [the releases table in the doc](https://docs.substra.org/en/latest/additional/release.html), leading to this workflow:
- open the "about" modal;
- check backend version;
- look for the corresponding bundle release in the table.
This PR simply automates that process by querying https://docs.substra.org/en/latest/releases.json and matching it with the version from the backend `/info` endpoint we already have.
Probably the easiest way is to go into `src/components/layout/header/About.tsx` and just write the values you like for the component versions:
```ts
// const {
//     info: {
//         version: backendVersion,
//         orchestrator_version: …
```
=> feat: display bundle version in "About" modal

CHANGELOG.md, src/routes/tasks/components/ErrorAlert.tsx, src/routes/tasks/components/LogsModal.tsx
* orchestrator: https://github.com/Substra/orchestrator/pull/310
* backend: https://github.com/Substra/substra-backend/pull/756
* frontend: https://github.com/Substra/substra-frontend/pull/240
* substra-generator: https://github.com/owkin/substra-generator/pull/131
Change the `LogsModal` to get a key, allowing to retrieve logs not directly linked with a compute task 
Changelog updated
=> feat: modify failure report

CHANGELOG.md, src/components/ComputePlanProgressBar.tsx, src/components/Timing.tsx, src/libs/status.ts, src/routes/computePlanDetails/ComputePlanUtils.ts, src/routes/computePlanDetails/workflow/CPWorkflowUtils.ts, src/routes/computePlanDetails/workflow/components/WorkflowTaskNode.tsx, src/routes/tasks/components/DrawerSectionOutModelEntryContent.tsx, src/routes/tasks/components/TaskOutputsDrawerSection.tsx, src/types/ComputePlansTypes.ts, src/types/TasksTypes.ts
- https://github.com/Substra/orchestrator/pull/366
- https://github.com/Substra/substra-tests/pull/319
- https://github.com/Substra/substra/pull/397
- https://github.com/Substra/substra-backend/pull/823
- https://github.com/Substra/substra-documentation/pull/390
Fixes FL-1397
=> feat!: add new compute tasks status linked to function status

CHANGELOG.md, src/routes/computePlanDetails/workflow/CPWorkflowLayout.spec.ts, src/routes/computePlanDetails/workflow/CPWorkflowLayout.ts
- https://github.com/Substra/substrafl/pull/177 (main)
- https://github.com/Substra/substra-documentation/pull/376
- https://github.com/Substra/substra-frontend/pull/268
=> chore: change max length secondary branch

.github/workflows/helm.yaml
Companion:
- https://github.com/Substra/substra-backend/pull/881
- https://github.com/Substra/orchestrator/pull/405
- https://github.com/Substra/substra-frontend/pull/333
Example of working worklfow (with fake publish):
- https://github.com/Substra/substra-backend/actions/runs/8628929572
=> chore: allow alpha charts publication

changes/1520.added, src/routes/tasks/TasksUtils.tsx, src/types/TasksTypes.ts
Add a new  task profiling step, `download_function` when the function owner is different from the worker and that the worker needs to download the function from the builder
Close FL-1520
- https://github.com/Substra/substra-backend/pull/883
=> feat: separate download function from execute task

changes/1517.removed, src/routes/tasks/TasksUtils.tsx, src/types/TasksTypes.ts
Remove the task profiling step `build_image`. The function will get its own profiling with different steps in another contribution.
Fixes FL-1517
- https://github.com/Substra/substra-backend/pull/884
=> chore: remove building from task profiling

changes/385.changed, src/routes/tokens/BearerTokenUtils.ts, src/routes/tokens/components/GenerateTokenModal.tsx, src/types/BearerTokenTypes.ts
Part of FL-1556 
https://github.com/Substra/substra-backend/pull/969
=> chore(token): disable never expiring tokens
