Substra/substra-frontend

- skaffold.yaml
Linked to https://github.com/SubstraFoundation/substra-backend/pull/35 and https://github.com/SubstraFoundation/hlf-k8s/pull/9
> Clean charts

- src/app/business/routes/model/components/detail/index.js
It looks like I missed a call to a an analytics function in #35
> Remove leftover analytics call

- src/app/business/routes/model/api.js
- src/app/business/routes/model/sagas/index.js
Companion PR to https://github.com/SubstraFoundation/substra-backend/pull/183
This PR replaces the use of `/model/<tuple_key>/details` with `/model/<tuple_key>`.
> Update model details route

- src/app/business/common/components/detail/components/title.js
- src/app/business/common/components/detail/index.js
- src/app/business/common/components/panel.js
> Fix responsive issue

- skaffold.yaml
Add a flag to enable deployment with Skaffold + Helm3.
> Helm3 compatibility

- src/app/common/components/detail/components/metadata.js
- src/app/common/components/detail/components/permissionsTabPanelContent.js
- src/app/routes/algo/components/index.js
- src/app/routes/algo/sagas/index.js
- src/app/routes/dataset/components/detail/components/tabs/index.js
- src/app/routes/dataset/components/index.js
- src/app/routes/dataset/components/list/components/popoverItems.js
- src/app/routes/dataset/sagas/index.js
- src/app/routes/model/components/detail/components/browseRelatedLinks.js
- src/app/routes/model/components/detail/components/metadata.js
- src/app/routes/model/components/list/components/popoverItems.js
- src/app/routes/model/selector.js
- src/app/routes/objective/components/index.js
- src/app/routes/objective/sagas/index.js
- src/app/search/fixtures/traintuples.js
- src/app/search/selector.js
Companion PR to https://github.com/SubstraFoundation/substra-backend/pull/315
> Snake_case

- src/app/routes/algo/reducers/item.js
- src/app/routes/objective/actions.js
- src/app/routes/objective/api.js
- src/app/routes/objective/components/detail/components/leaderboard.js
- src/app/routes/objective/components/detail/components/tabs/index.js
- src/app/routes/objective/components/detail/components/tabs/redux.js
- src/app/routes/objective/reducers/item.js
- src/app/routes/objective/sagas/index.js
- src/app/utils/fetchEntities.js
Adds a leaderboard tab to the objective details pane.
> Leaderboard

- src/app/routes/model/components/detail/components/browseRelatedLinks.js
- src/app/routes/model/components/detail/components/metadata.js
- src/app/routes/model/components/list/components/popoverItems.js
- src/app/routes/objective/components/detail/components/leaderboard.js
- src/app/search/fixtures/filters.js
- src/app/search/fixtures/modelsFilters.js
- src/app/search/fixtures/traintuples.js
- src/app/search/selector.js
This PR addresses the changes from https://github.com/SubstraFoundation/substra-backend/pull/342 and https://github.com/SubstraFoundation/substra-backend/pull/345
> Fixes related to the renaming from hash to key/checksum

- charts/substra-frontend/Chart.yaml
This adds some metadata to the chart definition.
> chore: add chart metadata

- CHANGELOG.md
- src/modules/tasks/ModelsTypes.ts
This removes the model category, which I believe is unused and will soon be removed.
I don't really know, tsc is happy so I guess I am too 🤷.
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1202936323744392
> feat: remove model category

- .github/pull_request_template.md
Add Asana link in GH template as it was done in connect frontend repo.
> feat: add Asana link in GH template

- CHANGELOG.md
- src/features/customColumns/useCustomColumns.ts
- src/hooks/useLocalStorageState.ts
- src/routes/computePlans/ComputePlans.tsx
Display the Generals CP columns by default.
> fix: display all general CP columns

- CHANGELOG.md
- src/components/PerfChartSummaryTooltip.tsx
Quick fix to tooltip placement on perfCard in computePlan performances page
> :bug: Fix rank tooltip on perfcards

- CHANGELOG.md
- src/components/layout/header/Header.tsx
- src/routes/users/Users.tsx
Rename Users Management by Users.
> feat: Rename Users Management by Users

- CHANGELOG.md
- src/routes/users/components/UpdateUserForm.tsx
Add missing deletion feedback in user management.
> feat: add missing deletion feedback

- CHANGELOG.md
- src/components/layout/header/Header.tsx
Fix link for users management in menu which only worked when clicking the text and not the whole button
> fix: Fix link for users management page

- CHANGELOG.md
- charts/substra-frontend/CHANGELOG.md
- charts/substra-frontend/Chart.yaml
- package.json
-   Prevent the last admin from being deleted
-   Rename Users Management by Users
-   Missing deletion feedback in user management
-   Disable edit user button if no change detected and rename it update
-   Fix rank tooltip on perfcards in CP performances page (#108)
-   Fix outdated refresh route in withRetry (#112)
-   Fix users management link in menu (#113)
-   Update task drawer inputs (#106)
> :bookmark: Release 0.35.0

- CHANGELOG.md
- charts/substra-frontend/CHANGELOG.md
- charts/substra-frontend/Chart.yaml
- package-lock.json
- package.json
-   CP workflow graph is now built independently of the task categories (#114)
-   Display user description after role update (#117)
-   Empty task inputs make drawer crash (#120)
> chore(release): 0.36.0

- CHANGELOG.md
- src/components/layout/header/Header.tsx
- Adds a documentation link to the User menu.
- Reorders items in the User menu.
> feat: add docs link

- .github/CODEOWNERS
Update code owners for substra-frontend
> chore: Update code owners

- CHANGELOG.md
- charts/substra-frontend/CHANGELOG.md
- charts/substra-frontend/Chart.yaml
- package-lock.json
- package.json
-   Update compute plan failed task key (#134)
-   User creation/edition validation (#133)
> chore: Release 0.38.0

- CHANGELOG.md
- charts/substra-frontend/CHANGELOG.md
- charts/substra-frontend/Chart.yaml
- package-lock.json
- package.json
-   Series grouping calcul & metric details page (#152)
> chore: Release 0.38.1

- CHANGELOG.md
- src/modules/algos/AlgosTypes.ts
- src/modules/datasets/DatasetsTypes.ts
- src/modules/datasets/DatasetsUtils.ts
- src/modules/perf/PerformancesTypes.ts
- src/modules/tasks/ModelsTypes.ts
- src/modules/tasks/ModelsUtils.ts
- src/modules/tasks/TasksApi.ts
- src/modules/tasks/TasksSlice.ts
- src/modules/tasks/TasksTypes.ts
- src/routes/algos/components/InputsOutputsDrawerSection.tsx
- src/routes/tasks/components/TaskDrawer.tsx
- src/routes/tasks/components/TaskInputsDrawerSection.tsx
- src/routes/tasks/components/TaskOutputsDrawerSection.tsx
Use new endpoints to get assets for task inputs & outputs
> chore: Use new input & output assets endpoints for tasks

- CHANGELOG.md
- charts/substra-frontend/CHANGELOG.md
- charts/substra-frontend/Chart.yaml
- package-lock.json
- package.json
-   Broken dataset details page (#168)
> chore: release 0.39.1

- CHANGELOG.md
- src/routes/tasks/components/ErrorAlert.tsx
Change current internal error message redirecting to Substra help slack channel for log access by a more appropriate message for all use cases.
> chore: Change internal error message

- CHANGELOG.md
- charts/substra-frontend/CHANGELOG.md
- charts/substra-frontend/Chart.yaml
- package-lock.json
- package.json
-   Internal error message (#172)
-   Broken dataset details page (#168)
> chore: release 0.39.2

- CHANGELOG.md
- src/components/DrawerSection.tsx
- src/components/TableFilterTags.tsx
- src/libs/utils.ts
- src/modules/tasks/TasksApi.ts
- src/modules/tasks/TasksSlice.ts
- src/modules/tasks/TasksTypes.ts
- src/modules/tasks/TasksUtils.ts
- src/routes/tasks/components/TaskDrawer.tsx
- src/routes/tasks/components/TaskDurationBar.tsx
Adds TaskDuration section to TaskDrawer in tasks page. 
- Displays the total task duration
- Displays the duration for each step of the task computing 
- Provides description of what is happening for each step in tooltip
- Doesn't display taskDuration if task isn't done but displays duration for each step currently done
Companion PR: https://github.com/Substra/substra-backend/pull/598
Need tasks data with task_profiling and open a task drawer
> feat: Task Duration

- CHANGELOG.md
- src/components/table/OrderingTh.tsx
Change the icon for list ordering in tables
> chore: Change list ordering icon

- src/App.tsx
When checking refreshToken, await the fetching of info, organizations and metadata before ending the loading. 
Small change that i forgot to add to the zustand refactor PR before merging.
> fix: Await fetch various info before ending load when checking refresh token

- CHANGELOG.md
- charts/substra-frontend/CHANGELOG.md
- charts/substra-frontend/Chart.yaml
- package-lock.json
- package.json
-   Serialize the performance graph regarding the identifier only (#194)
-   Display the cause of CP not being cancellable in tooltip (#192)
-   Display function name for each task in workflow & tasks table (#188)
-   Upgrade node version from 16.13.0 to 18.16.0 (#187)
-   New icon for list ordering in tables (#191)
-   CP cancel alert message (#192)
-   Inverted duration filter in tasks table (#190)
-   Big refactor to use zustand instead of redux to handle store (#159)
-   Change files architecture (#159)
-   Better performances for workflow (#196)
> chore: release 0.41.0

- CHANGELOG.md
- charts/substra-frontend/CHANGELOG.md
- charts/substra-frontend/Chart.yaml
- package-lock.json
- package.json
> chore: release 0.42.0

- src/routes/computePlanDetails/workflow/components/WorkflowTaskNode.tsx
In the workflow graph, handles are not correctly aligned with their respective labels for inputs and outputs. This PR increases the hardcoded margins between handles to better this alignement. 
Fixes FL-1060
> fix: Align inputs/outputs with their label in workflow

- .github/dependabot.yml
- CHANGELOG.md
- docker/substra-frontend/Dockerfile
Upgrading nginx fixes several CVEs in our product.
To ensure we don't fall behind, also configure dependabot to upgrade Docker and NPM dependencies.
> chore: upgrade nginx and configure dependabot

- CHANGELOG.md
- charts/substra-frontend/CHANGELOG.md
- charts/substra-frontend/Chart.yaml
- package-lock.json
- package.json
> chore: release 0.45.1

- package-lock.json
- package.json
Bump trivago/prettier version to 4.2.0
Fixes FL-1247
> bump trivago/prettier to 4.2.0

- CHANGELOG.md
- src/routes/functions/components/FunctionDrawer.tsx
- src/routes/tasks/components/TaskDrawer.tsx
- src/types/FunctionsTypes.ts
> feat!: rename `function.function` in `function.archive`

- CHANGELOG.md
- charts/substra-frontend/CHANGELOG.md
- charts/substra-frontend/Chart.yaml
- package-lock.json
- package.json
> release: 0.47.0

- CHANGELOG.md
- src/components/ComputePlanTaskStatuses.tsx
- src/components/table/TasksTable.tsx
- src/routes/computePlanDetails/workflow/components/WorkflowTaskNode.tsx
- src/types/TasksTypes.ts
> feat: update style for new task statuses

- .github/workflows/helm.yaml
https://github.com/Substra/substra-frontend/pull/302#discussion_r1509226590
> chore: revert helm workflow triggers

- docker/substra-frontend/Dockerfile
Pass from: 
- 2 critical, 28 hight, 157 in total 
To:
- 1 critical, 9 high, 95 total
> chore: reduce number of CVEs in docker image

- charts/substra-frontend/CHANGELOG.md
- charts/substra-frontend/Chart.yaml
- charts/substra-frontend/values.yaml
> chore: add resources limits and requests to containers

- docker/substra-frontend/Dockerfile
> chore: reduce number of CVEs in docker image second round

- changes/1528.fixed
- src/routes/tasks/TasksUtils.tsx
- src/routes/tasks/components/TaskDurationBar.tsx
> feat: fix task profiling order

- charts/substra-frontend/CHANGELOG.md
- charts/substra-frontend/Chart.yaml
- charts/substra-frontend/templates/networkpolicy.yaml
> feat: add network policy

- charts/substra-frontend/CHANGELOG.md
- charts/substra-frontend/Chart.yaml
- charts/substra-frontend/templates/deployment.yaml
- charts/substra-frontend/values.yaml
> chore: enforce restricted PSS

- changes/1410.added
- src/api/ProfilingApi.ts
- src/api/TasksApi.ts
- src/components/ProfilingDurationBar.tsx
- src/paths.ts
- src/routes/functions/FunctionsUtils.ts
- src/routes/functions/components/FunctionDrawer.tsx
- src/routes/functions/components/FunctionDurationBar.tsx
- src/routes/functions/useFunctionStore.tsx
- src/routes/tasks/TasksUtils.tsx
- src/routes/tasks/components/TaskDrawer.tsx
- src/routes/tasks/components/TaskDurationBar.tsx
- src/routes/tasks/useTaskStore.tsx
- src/types/FunctionsTypes.ts
- src/types/ProfilingTypes.ts
- src/types/TasksTypes.ts
> feat: function profiling

- changes/386.fixed
- src/routes/computePlanDetails/workflow/components/TasksWorkflow.tsx
> feat: zoom on building tasks

- package-lock.json
- package.json
> fix(deps): revert `@chakra-ui/react` to 2.6.1
